services:
  - type: web
    name: depressiondetection-2210990832-2210990158
    runtime: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd SourceCode/backend-node && node server.js
    envVars:
      - key: NODE_ENV
        value: production
